# Generated by Django 3.2.9 on 2022-11-05 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyric',
            name='song_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='song',
            name='artiste_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='song',
            name='likes',
            field=models.IntegerField(),
        ),
    ]
